# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
gems: [jekyll-paginate]
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus:
google_analytics: UA-60673588-1

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Cyber Security Blog

description: CTF Writeups
author:
  name: syedfarazabrar.com
  email: faraz.abrar9@gmail.com
  github: farazsth98
  hackthebox: faithlesss
#  twitter:
#  pinterest:
#  linkedin:
  bio: Cyber Security Student at Curtin University. I regularly participate in CTFs and bug bounties. I love pwn and RE challenges :D
  email_md5: 6be70bef138ac815dbdb9354b71230f3

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

future: false
