title: Syed Faraz Abrar | Security Blog
baseurl: "/"
url: "https://syedfarazabrar.com"
future: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown
  - rouge

markdown: kramdown
highlighter: rouge
