title: Syed Faraz Abrar | Security Blog
baseurl: "/"
url: "https://www.syedfarazabrar.com"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown
  - rouge

markdown: kramdown
highlighter: rouge
